
package mysqldb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanan
 */
public class InterfazQuery extends javax.swing.JFrame {
    String rutaConexion = "jdbc:mysql://localhost/driverol?"+"user=root&password=1234";
    PreparedStatement ps;
    public InterfazQuery() {
        initComponents();
        txtID.setVisible(false);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultasPredis = new javax.swing.JComboBox<>();
        campoConsultaManual = new javax.swing.JTextField();
        Select = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtRolNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInsertLibros = new javax.swing.JButton();
        btnModifLibros = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCleanLibros = new javax.swing.JButton();
        btnShowLibros = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyecto DB-Rol");

        consultasPredis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona consulta diseñada", "Mostrar Libros", "Mostrar Jugadores", "Mostrar Juegos Rol", "Mostrar Partidas", " " }));
        consultasPredis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasPredisActionPerformed(evt);
            }
        });

        campoConsultaManual.setText("Introduce tu consulta aquí.");
        campoConsultaManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaManualActionPerformed(evt);
            }
        });

        Select.setBackground(new java.awt.Color(140, 240, 240));
        Select.setText("Execute");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });

        Limpiar.setBackground(new java.awt.Color(50, 140, 0));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        Cerrar.setBackground(new java.awt.Color(200, 50, 30));
        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultasPredis, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Select, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(campoConsultaManual))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultasPredis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoConsultaManual, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Select, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Selects", jPanel1);

        txtTitulo.setText("Titulo");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtIdioma.setText("Idioma");

        txtRolNombre.setText("Rol");

        jLabel2.setText("Titulo");

        jLabel3.setText("Idioma");

        jLabel4.setText("Categoria Libro");

        jLabel5.setText("Juego Rol");

        btnInsertLibros.setText("Insertar");
        btnInsertLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertLibrosActionPerformed(evt);
            }
        });

        btnModifLibros.setText("Modificar");
        btnModifLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifLibrosActionPerformed(evt);
            }
        });

        jLabel6.setText("Formulario Insertar y modificar Libros");

        btnCleanLibros.setText("Limpiar");
        btnCleanLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanLibrosActionPerformed(evt);
            }
        });

        btnShowLibros.setText("Mostrar");
        btnShowLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLibrosActionPerformed(evt);
            }
        });

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elije una categoría", "Basico", "Suplemento", "Utilidades", "Novela" }));

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtID.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInsertLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtIdioma, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRolNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowLibros)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("Insertar Libros", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed

    }//GEN-LAST:event_CerrarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        campoConsultaManual.setText("Inserte aquí su consulta SQL");
        DefaultTableModel dm = (DefaultTableModel)tabla.getModel();
        
        while(dm.getRowCount() > 0) {
    dm.removeRow(0);
}
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed

        String nuevoQuery = campoConsultaManual.getText();
        Connection conex = Conexion.conectarse(rutaConexion);
        String[] columnas = null;
        String[] registros = null;

         
        if (conex != null) {
            Statement sentencia = null;
            ResultSet result = null;
        try {
            sentencia = conex.createStatement();
            if (sentencia.execute(nuevoQuery)) {
                result = sentencia.getResultSet();
                ResultSetMetaData rsmd = result.getMetaData();
                int columnsNumber = rsmd.getColumnCount();
                registros = new String[columnsNumber+1];
                columnas = new String[columnsNumber+1];
                 for (int i = 1; i < (columnsNumber+1); i++) {
                        columnas[i] = rsmd.getColumnName(i);
                    }
                 DefaultTableModel model = new DefaultTableModel(null, columnas);
                while (result.next()) {
                    for (int i = 1; i < (columnsNumber+1); i++) {
                        System.out.print(rsmd.getColumnName(i)+" "+result.getString(i) + " ");
                        registros[i] = result.getString(i);
                    }
                    model.addRow(registros);
                    System.out.println();
                }        
                tabla.setModel(model);
                
            }
        } catch(SQLException except) {
            System.out.println("SQLException: " + except.getMessage());
            System.out.println("SQLState: " + except.getSQLState());
            System.out.println("VendorError: " + except.getErrorCode());
} finally {
            if (result != null) {
                try {
                    result.close();
                } catch (SQLException sqlEx) {
                } // ignore

                result = null;
            }

            if (sentencia != null) {
                try {
                    sentencia.close();
                } catch (SQLException sqlEx) {
                } // ignore

                sentencia = null;
            }

            if (conex != null) {
                try {
                    conex.close();
                } catch (SQLException sqlEx) {
                } // ignore

                conex = null;
            }

            }}
    }//GEN-LAST:event_SelectActionPerformed

    private void campoConsultaManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaManualActionPerformed
    }
    private  void updateTextBox()
{
    if (consultasPredis.getSelectedIndex() == 1) {
        campoConsultaManual.setText("SELECT * FROM libros;");

    } else if (consultasPredis.getSelectedIndex() == 2) {
        campoConsultaManual.setText("SELECT * FROM jugador;");
    } else if (consultasPredis.getSelectedIndex() == 3) {
        campoConsultaManual.setText("SELECT * FROM rol;");
    } else if (consultasPredis.getSelectedIndex() == 4) {
        campoConsultaManual.setText("SELECT * FROM partida;");
    }
    }//GEN-LAST:event_campoConsultaManualActionPerformed

    private void consultasPredisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasPredisActionPerformed
        updateTextBox();
    }//GEN-LAST:event_consultasPredisActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnInsertLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertLibrosActionPerformed

            try {
                       Connection conex = Conexion.conectarse(rutaConexion);
                       ps = conex.prepareStatement("INSERT INTO libros (Titulo, Idioma, categoria, rol_Nombre) VALUES (?, ?, ?, ?);");
                       ps.setString(1, txtTitulo.getText());
                       ps.setString(2, txtIdioma.getText());
                       ps.setString(3, cbxCategoria.getSelectedItem().toString());
                       ps.setString(4, txtRolNombre.getText());
                       
                       int res = ps.executeUpdate();
                       if (res >0) {
                           JOptionPane.showInputDialog(null, "Libro añadido");
                           limpiarCajas();
                       } else {
                           JOptionPane.showInputDialog(null, "Error al añadir libro");
                           limpiarCajas();
                       }
                       
                       conex.close();
                       
        } catch (Exception e) {
                System.err.print(e);
        }
    }//GEN-LAST:event_btnInsertLibrosActionPerformed

    private void btnCleanLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanLibrosActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_btnCleanLibrosActionPerformed

    private void btnModifLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifLibrosActionPerformed
        
            try {
                       Connection conex = Conexion.conectarse(rutaConexion);
                       ps = conex.prepareStatement("UPDATE libros SET Titulo=?, Idioma=?, categoria=?, rol_Nombre=? WHERE idLibros = ?");
                       ps.setString(1, txtTitulo.getText());
                       ps.setString(2, txtIdioma.getText());
                       ps.setString(3, cbxCategoria.getSelectedItem().toString());
                       ps.setString(4, txtRolNombre.getText());
                       ps.setString(5, txtID.getText());
                       
                       int res = ps.executeUpdate();
                       if (res >0) {
                           JOptionPane.showInputDialog(null, "Libro modificado");
                           limpiarCajas();
                       } else {
                           JOptionPane.showInputDialog(null, "Error al modificar libro");
                           limpiarCajas();
                       }
                       
                       conex.close();
                       
        } catch (Exception e) {
                System.err.print(e);
        }
    }//GEN-LAST:event_btnModifLibrosActionPerformed

    private void btnShowLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLibrosActionPerformed

        try {
            Connection conex = Conexion.conectarse(rutaConexion);
            ResultSet result = null;
            ps = conex.prepareStatement("SELECT * FROM libros WHERE Titulo = ?");
            ps.setString(1, txtTitulo.getText());
            result = ps.executeQuery();
            if (result.next()) {
                txtTitulo.setText(result.getString("Titulo"));
                txtIdioma.setText(result.getString("Idioma"));
                txtRolNombre.setText(result.getString("rol_Nombre"));
                cbxCategoria.setSelectedItem(result.getString("categoria"));
                txtID.setText(result.getString("idLibros"));
               
            } else {
                JOptionPane.showInputDialog(null, "No existe libro con ese Titulo!!");
            }
        }catch (Exception e) {
                System.err.print(e);
        }
    }//GEN-LAST:event_btnShowLibrosActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         try {
                       Connection conex = Conexion.conectarse(rutaConexion);
                       ps = conex.prepareStatement("DELETE FROM libros WHERE idLibros = ?");
                       ps.setInt(1,Integer.parseInt(txtID.getText()));
                       
                       int res = ps.executeUpdate();
                       if (res >0) {
                           JOptionPane.showInputDialog(null, "Libro eliminado");
                       } else {
                           JOptionPane.showInputDialog(null, "Error al eliminar libro");
                       }
                       
                       conex.close();
                       
        } catch (Exception e) {
                System.err.print(e);
        }                                  
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void limpiarCajas() {
        txtTitulo.setText(null);
        txtIdioma.setText(null);
        txtRolNombre.setText(null);
        cbxCategoria.setSelectedIndex(0);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazQuery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Select;
    private javax.swing.JButton btnCleanLibros;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsertLibros;
    private javax.swing.JButton btnModifLibros;
    private javax.swing.JButton btnShowLibros;
    private javax.swing.JTextField campoConsultaManual;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> consultasPredis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtRolNombre;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
