INSERT INTO driverol.libros
  (Titulo,Idioma,rol_Nombre,categoria)
VALUES
  ('Anima Beyond Fantasy - Dominus Exxet.pdf','Castellano','Anima Beyond Fantasy','Suplemento'),
  ('Anima Beyond Fantasy - Core Exxet.pdf','Castellano','Anima Beyond Fantasy','Basico'),
  ('Anima Beyond Fantasy - Arcana Exxet.pdf','Castellano','Anima Beyond Fantasy','Suplemento'),
  ('Ficha Extra Psiquico 2.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Extra Psiquico 1.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Extra Magia.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Extra Ki.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Extra Base.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Ampliada.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha BlackZerg.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('Ficha Extra Convocación.pdf','Castellano','Anima Beyond Fantasy','Utilidades'),
  ('La Leyenda de los Cinco Anillos.pdf','Castellano','La leyenda de los 5 anillos','Basico'),
  ('Nuevas-tablas-de-herencia.pdf','Castellano','La leyenda de los 5 anillos','Utilidades'),
  ('Hoja-de-personaje.pdf','Castellano','La leyenda de los 5 anillos','Utilidades'),
  ('Mapa-rokugan.pdf','Castellano','La leyenda de los 5 anillos','Utilidades'),
  ('Tablas-de-encuentros.pdf','Castellano','La leyenda de los 5 anillos','Utilidades'),
  ('Tablas-de-herencia.pdf','Castellano','La leyenda de los 5 anillos','Utilidades'),
  ('Vampiro - Gehena, La Ultima Noche.pdf','Castellano','Vampiro la mascarada ','Novela'),
  ('Mago - El Dia del Juicio.pdf','Castellano','Mago la ascension','Novela'),
  ('Hombre Lobo - La Ultima Batalla.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('4 - Setita.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('14 - Antologia.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('13 - Nosferatu.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('9 - Malkavian.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('6 - Lasombra.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('7 - Assamita.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('8 - Ravnos.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('2 - Tzimisce.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('3 - Gangrel.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('12 - Tremere.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('10 - Giovanni.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('11 - Brujah.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('5 - Ventrue.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('1 - Toreador.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('Triologia Lasombra - 2 - Sombras.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('Triologia Lasombra - 1 - Señales.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('Triologia Lasombra - 3 - Sacrificios.pdf','Castellano','Vampiro la mascarada','Novela'),
  ('7 Roehuesos.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('8 Contemplaestrellas.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('9 Hijos de Gaia.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('5 Garras Rojas.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('4 Furias Negras.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('3 Caminantes Silenciosos.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('14 Wendigo.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('6 Fianna.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('2 Camada de Fenris.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('12 Moradores del Cristal.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('10 Uktena.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('11 Colmillos Plateados.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('13 Danzantes de la espiral Negra.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('1 Señores de la sombra.pdf','Castellano','Hombrelobo el apocalipsis','Novela'),
  ('Hombre Lobo 20 Aniversario.pdf','Castellano','Hombrelobo el apocalipsis','Basico'),
  ('Razas Cambiantes.pdf','Castellano','Hombrelobo el apocalipsis','Suplemento'),
  ('Rabia por el mundo.pdf','Castellano','Hombrelobo el apocalipsis','Suplemento'),
  ('Pantalla - Hombre Lobo 20 Aniversario.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Fichas - Cuaderno Razas.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Ficha - Hombre Lobo 20.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Swara.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Simba.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Rokea.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Ratkin.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Qualmi.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Pumonca.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Nuwisha.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Nagah.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Mokolé.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Kitsune.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Khan.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Gurahl.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Corax.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Ceilican.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Bubasti.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Bastet.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Balam.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Bagheera.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Ananasi.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Ajaba.pdf','Castellano','Hombrelobo el apocalipsis','Utilidades'),
  ('Vampiro Edad Oscura.pdf','Castellano','Vampiro Edad Oscura','Basico'),
  ('Pantalla del Narrador.pdf','Castellano','Vampiro Edad Oscura','Utilidades'),
  ('Fichas - Clanes.pdf','Castellano','Vampiro Edad Oscura','Utilidades'),
  ('Anexo - Glosario.pdf','Castellano','Vampiro la mascarada','Utilidades'),
  ('Ficha - Básica.pdf','Castellano','Vampiro la mascarada','Utilidades'),
  ('Saber de los Clanes.pdf','Castellano','Vampiro la mascarada','Suplemento'),
  ('Nombres temibles - Lista Roja.pdf','Castellano','Vampiro la mascarada','Suplemento'),
  ('Cazadores Cazados.pdf','Castellano','Vampiro la mascarada','Suplemento'),
  ('Anarquistas liberados.pdf','Castellano','Vampiro la mascarada','Suplemento'),
  ('Ficha - Clanes.pdf','Castellano','Vampiro la mascarada','Utilidades'),
  ('Basico - Vampiro 20 Aniversario.pdf','Castellano','Vampiro la mascarada','Basico'),
  ('Ayuda - Estado de Pjs.pdf','Castellano','Vampiro la mascarada','Utilidades'),
  ('Suplemento V20 - Pantalla del Narrador.pdf','Castellano','Vampiro la mascarada','Utilidades'),
  ('Ficha Editable El resurgir del dragón.pdf','Castellano','El resurgir del dragón','Utilidades'),
  ('Ficha Autocalculable El resurgir del dragón.pdf','Castellano','El resurgir del dragón','Utilidades'),
  ('Ficha Editable El Resurgir Del Dragon color.pdf','Castellano','El resurgir del dragón','Utilidades'),
  ('resurgirdeldragon-mapa-voldor.pdf','Castellano','El resurgir del dragón','Utilidades'),
  ('Resurgir-dragon-ficha_jugador-web-BN.pdf','Castellano','El resurgir del dragón','Utilidades'),
  ('Elresurgirdeldragonebook.pdf','Castellano','El resurgir del dragón','Basico'),
  ('Resurgir-dragon-ficha_jugador-web-color.pdf','Castellano','El resurgir del dragón','Utilidades');
