-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 22:40:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoBD` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoBD` ;

-- -----------------------------------------------------
-- Table `ProyectoBD`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edición` VARCHAR(45) NULL,
  `Ambientación` ENUM('Fantasía', 'Ciencia Ficción', 'Terror', 'Realidad Alternativa', 'Historico', 'Historico Fantastico') NULL COMMENT 'ENUM(\'Fantasía\',\'Ciencia Ficción\',\'Terror\',\'Realidad Alternativa\',\'Historico\',\'Historico Fantastico\')',
  `Época` ENUM('Actual', 'Medieval', 'Futuro') NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoBD`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Partida` (
  `idPartida` INT NOT NULL,
  `Cronica` VARCHAR(45) NOT NULL,
  `Jugadores` INT NULL,
  `Rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cronica`, `Rol_Nombre`),
  UNIQUE INDEX `Cronica_UNIQUE` (`Cronica` ASC),
  INDEX `fk_Partida_Rol1_idx` (`Rol_Nombre` ASC),
  CONSTRAINT `fk_Partida_Rol1`
    FOREIGN KEY (`Rol_Nombre`)
    REFERENCES `ProyectoBD`.`Rol` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoBD`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Jugador` (
  `idJugador` INT NOT NULL AUTO_INCREMENT,
  `Apodo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Partida_Cronica` VARCHAR(45) NOT NULL,
  `Partida_Rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Apodo`, `Partida_Cronica`, `Partida_Rol_Nombre`),
  INDEX `fk_Jugador_Partida1_idx` (`Partida_Cronica` ASC, `Partida_Rol_Nombre` ASC),
  CONSTRAINT `fk_Jugador_Partida1`
    FOREIGN KEY (`Partida_Cronica` , `Partida_Rol_Nombre`)
    REFERENCES `ProyectoBD`.`Partida` (`Cronica` , `Rol_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoBD`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Libros` (
  `idLibros` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Idioma` VARCHAR(45) NULL,
  `Rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rol_Nombre`, `Nombre`),
  INDEX `fk_Libros_Rol_idx` (`Rol_Nombre` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  CONSTRAINT `fk_Libros_Rol`
    FOREIGN KEY (`Rol_Nombre`)
    REFERENCES `ProyectoBD`.`Rol` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoBD`.`Juega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Juega` (
  `Jugador_Apodo` VARCHAR(45) NOT NULL,
  `Rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Jugador_Apodo`, `Rol_Nombre`),
  INDEX `fk_Jugador_has_Rol_Rol1_idx` (`Rol_Nombre` ASC),
  INDEX `fk_Jugador_has_Rol_Jugador1_idx` (`Jugador_Apodo` ASC),
  CONSTRAINT `fk_Jugador_has_Rol_Jugador1`
    FOREIGN KEY (`Jugador_Apodo`)
    REFERENCES `ProyectoBD`.`Jugador` (`Apodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_has_Rol_Rol1`
    FOREIGN KEY (`Rol_Nombre`)
    REFERENCES `ProyectoBD`.`Rol` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoBD`.`Usa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoBD`.`Usa` (
  `Libros_Rol_Nombre` VARCHAR(45) NOT NULL,
  `Libros_Nombre` VARCHAR(45) NOT NULL,
  `Partida_Cronica` VARCHAR(45) NOT NULL,
  `Partida_Rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Libros_Rol_Nombre`, `Libros_Nombre`, `Partida_Cronica`, `Partida_Rol_Nombre`),
  INDEX `fk_Libros_has_Partida_Partida1_idx` (`Partida_Cronica` ASC, `Partida_Rol_Nombre` ASC),
  INDEX `fk_Libros_has_Partida_Libros1_idx` (`Libros_Rol_Nombre` ASC, `Libros_Nombre` ASC),
  CONSTRAINT `fk_Libros_has_Partida_Libros1`
    FOREIGN KEY (`Libros_Rol_Nombre` , `Libros_Nombre`)
    REFERENCES `ProyectoBD`.`Libros` (`Rol_Nombre` , `Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros_has_Partida_Partida1`
    FOREIGN KEY (`Partida_Cronica` , `Partida_Rol_Nombre`)
    REFERENCES `ProyectoBD`.`Partida` (`Cronica` , `Rol_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
