-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 22:59:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyectobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectobd` DEFAULT CHARACTER SET utf8 ;
USE `proyectobd` ;

-- -----------------------------------------------------
-- Table `proyectobd`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`jugador` (
  `idJugador` INT(11) NOT NULL AUTO_INCREMENT,
  `Apodo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idJugador`, `Apodo`),
  UNIQUE INDEX `idJugador_UNIQUE` (`idJugador` ASC),
  UNIQUE INDEX `Apodo_UNIQUE` (`Apodo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyectobd`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`rol` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edición` VARCHAR(45) NULL DEFAULT NULL,
  `Ambientación` ENUM('Fantasía', 'Ciencia Ficción', 'Terror', 'Realidad Alternativa', 'Historico', 'Historico Fantastico') NULL DEFAULT NULL COMMENT 'ENUM(\'Fantasía\',\'Ciencia Ficción\',\'Terror\',\'Realidad Alternativa\',\'Historico\',\'Historico Fantastico\')',
  `Época` ENUM('Actual', 'Medieval', 'Futuro') NULL DEFAULT NULL,
  PRIMARY KEY (`idRol`, `Nombre`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyectobd`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`libros` (
  `idLibros` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Idioma` VARCHAR(45) NULL DEFAULT NULL,
  `categoría` ENUM('Básico', 'Suplemento', 'Utilidades') NULL DEFAULT NULL,
  `rol_idRol` INT(11) NOT NULL,
  `rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `idLibros`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `idLibros_UNIQUE` (`idLibros` ASC),
  INDEX `fk_libros_rol_idx` (`rol_idRol` ASC, `rol_Nombre` ASC),
  CONSTRAINT `fk_libros_rol`
    FOREIGN KEY (`rol_idRol` , `rol_Nombre`)
    REFERENCES `proyectobd`.`rol` (`idRol` , `Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyectobd`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`partida` (
  `idPartida` INT(11) NOT NULL AUTO_INCREMENT,
  `Cronica` VARCHAR(45) NOT NULL,
  `Jugadores` INT(11) NULL DEFAULT NULL,
  `rol_idRol` INT(11) NOT NULL,
  `rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cronica`, `rol_idRol`, `rol_Nombre`),
  UNIQUE INDEX `idPartida_UNIQUE` (`idPartida` ASC),
  UNIQUE INDEX `Cronica_UNIQUE` (`Cronica` ASC),
  INDEX `fk_partida_rol1_idx` (`rol_idRol` ASC, `rol_Nombre` ASC),
  CONSTRAINT `fk_partida_rol1`
    FOREIGN KEY (`rol_idRol` , `rol_Nombre`)
    REFERENCES `proyectobd`.`rol` (`idRol` , `Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyectobd`.`Juega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`Juega` (
  `jugador_idJugador` INT(11) NOT NULL,
  `jugador_Apodo` VARCHAR(45) NOT NULL,
  `partida_Cronica` VARCHAR(45) NOT NULL,
  `partida_rol_idRol` INT(11) NOT NULL,
  `partida_rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`jugador_idJugador`, `jugador_Apodo`, `partida_Cronica`, `partida_rol_idRol`, `partida_rol_Nombre`),
  INDEX `fk_jugador_has_partida_partida1_idx` (`partida_Cronica` ASC, `partida_rol_idRol` ASC, `partida_rol_Nombre` ASC),
  INDEX `fk_jugador_has_partida_jugador1_idx` (`jugador_idJugador` ASC, `jugador_Apodo` ASC),
  UNIQUE INDEX `jugador_idJugador_UNIQUE` (`jugador_idJugador` ASC),
  UNIQUE INDEX `jugador_Apodo_UNIQUE` (`jugador_Apodo` ASC),
  UNIQUE INDEX `partida_rol_Nombre_UNIQUE` (`partida_rol_Nombre` ASC),
  CONSTRAINT `fk_jugador_has_partida_jugador1`
    FOREIGN KEY (`jugador_idJugador` , `jugador_Apodo`)
    REFERENCES `proyectobd`.`jugador` (`idJugador` , `Apodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_has_partida_partida1`
    FOREIGN KEY (`partida_Cronica` , `partida_rol_idRol` , `partida_rol_Nombre`)
    REFERENCES `proyectobd`.`partida` (`Cronica` , `rol_idRol` , `rol_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyectobd`.`Usa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`Usa` (
  `libros_Nombre` VARCHAR(45) NOT NULL,
  `libros_idLibros` INT(11) NOT NULL,
  `partida_Cronica` VARCHAR(45) NOT NULL,
  `partida_rol_idRol` INT(11) NOT NULL,
  `partida_rol_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`libros_Nombre`, `libros_idLibros`, `partida_Cronica`, `partida_rol_idRol`, `partida_rol_Nombre`),
  INDEX `fk_libros_has_partida_partida1_idx` (`partida_Cronica` ASC, `partida_rol_idRol` ASC, `partida_rol_Nombre` ASC),
  INDEX `fk_libros_has_partida_libros1_idx` (`libros_Nombre` ASC, `libros_idLibros` ASC),
  UNIQUE INDEX `partida_rol_idRol_UNIQUE` (`partida_rol_idRol` ASC),
  CONSTRAINT `fk_libros_has_partida_libros1`
    FOREIGN KEY (`libros_Nombre` , `libros_idLibros`)
    REFERENCES `proyectobd`.`libros` (`Nombre` , `idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_partida_partida1`
    FOREIGN KEY (`partida_Cronica` , `partida_rol_idRol` , `partida_rol_Nombre`)
    REFERENCES `proyectobd`.`partida` (`Cronica` , `rol_idRol` , `rol_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
